# Generated by Django 3.0.2 on 2020-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_auto_20200408_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationclient',
            name='nametodisplay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destinationclient',
            name='req',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
