# Generated by Django 3.0.2 on 2020-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0005_auto_20200408_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcompany',
            name='organizationname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
