# Generated by Django 3.0.2 on 2020-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0006_destinationcompany_organizationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationclient',
            name='notification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
