# Generated by Django 3.0.2 on 2020-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0007_destinationclient_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='skills',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
